"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RmBoxMwQRgs
 */
import Link from "next/link"
import { JSX, SVGProps } from "react"
import { useRouter } from 'next/navigation';

export function Header() {
  const router = useRouter();
  return (
    <header className="flex items-center w-full px-4 py-4 md:py-6 border-b">
      <div className="flex items-center space-x-4">
        <Link className="flex items-center space-x-2" href="#">
          <BoxIcon className="w-6 h-6" />
          <span className="font-bold tracking-widest">Election Commission</span>
        </Link>
      </div>
      <nav className="ml-auto flex items-center space-x-4">
        <Link
          className="font-medium underline border-b-2 border-transparent hover:border-gray-900 hover:text-gray-900"
          href="/"
        >
          View Live Poll
        </Link>
        <Link
          className="inline-flex items-center justify-center h-9 w-24 border border-gray-200 border-gray-200 font-medium rounded-md bg-white shadow-sm hover:shadow transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-950"
          href="/pages/log-in"
        >
          Log In
        </Link>
        <Link
          className="inline-flex items-center justify-center h-9 w-32 border border-gray-200 border-gray-200 font-medium rounded-md bg-gray-900 text-gray-50 shadow-sm hover:shadow transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-950"
          href="/pages/sign-up"
        >
          Register to Vote
        </Link>
      </nav>
    </header>
  )
}


function BoxIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 8a2 2 0 0-1-1.73l-7-4a2 0-2 0l-7 4A2 3 8v8a2 1 1.73l7 4a2 0l7-4A2 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}
