/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fys31EXTsov
 */
 import { Label } from "@/components/ui/label"
 import { Input } from "@/components/ui/input"
 import { Button } from "@/components/ui/button"
 import { Separator } from "@/components/ui/separator"
 import Link from "next/link"
 import { JSX, SVGProps } from "react"
 import { Header } from "@/components/header"
 
 export function LogIn() {
   return (
     <div>
        <Header />
        <div className="mx-auto max-w-[350px] space-y-6">
            <div className="space-y-2 text-center">
                <h1 className="text-3xl font-bold">Login</h1>
                <p className="text-gray-500 dark:text-gray-400">Enter your details to register.</p>
            </div>
            <div className="space-y-4">
                <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="m@example.com" required type="email" />
                </div>
                <div className="space-y-2 relative">
                    <div className="space-y-1">
                        <Label htmlFor="password">Password</Label>
                        <div className="relative">
                            <Input id="password" required type="password" />
                            <div className="flex items-center -translate-y-1.5 absolute right-2 top-1/2 transform -translate-y-1/2">
                                <Button
                                aria-label="Toggle password visibility"
                                className="h-8 p-1.5 -translate-y-0.5 w-8"
                                variant="ghost"
                                >
                                    <EyeIcon className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
                <Button className="w-full" type="submit">
                Login
                </Button>
            </div>
            <Separator className="mb-0" />
            <div className="space-y-2 text-center">
                <p className="text-sm">
                Not a registered voter?
                <Link className="underline" href="/sign-up">
                    Register
                </Link>
                </p>
            </div>
        </div>
     </div>
     
   )
 }
 
 
 function EyeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
   return (
     <svg
       {...props}
       xmlns="http://www.w3.org/2000/svg"
       width="24"
       height="24"
       viewBox="0 24"
       fill="none"
       stroke="currentColor"
       strokeWidth="2"
       strokeLinecap="round"
       strokeLinejoin="round"
     >
       <path d="M2 12s3-7 10-7 10 7 7-3 7-10 7-10-7-10-7Z" />
       <circle cx="12" cy="12" r="3" />
     </svg>
   )
 }

 export default LogIn;
 