/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n5PcaL2qzZg
 */
"use client";
 import { CardTitle, CardDescription, CardContent, CardFooter, Card } from "@/components/ui/card"
 import { Button } from "@/components/ui/button"
 import { Header } from "@/components/header"
 import Image from 'next/image';
 import { collection, doc, getDocs, updateDoc } from 'firebase/firestore';
import { db } from '@/app/firebase/config';
import { useEffect, useState } from "react";
 
interface Candidate {
  id: string;
  name: string;
  imageSrc: string;
  votes: number;

}

const getCandidatesData = async () => {
  try {
    const candidatesCollection = collection(db, 'candidates');
    const querySnapshot = await getDocs(candidatesCollection);

    // Extract data from each document
    const candidatesData = querySnapshot.docs.map((doc) => ({
      id: doc.id,
      name: doc.data().name,
      imageSrc: doc.data().imageSrc,
      votes: doc.data().votes,
    }));

    return candidatesData;
  } catch (error) {
    console.error('Error fetching candidates data:');
    return [];
  }
};

 export function Vote() {

   const [candidates, setCandidates] = useState<Candidate[]>([]);

   useEffect(() => {
    const fetchData = async () => {
      const candidatesData = await getCandidatesData();
      setCandidates(candidatesData);
    };

    fetchData();
  }, []);
  
  const handleVoteClick = async (candidateId: string) => {
   
    try {
      // Update the votes for the candidate in Firestore
      const candidateRef = doc(db, 'candidates', candidateId);
      
      const foundCandidate = candidates.find((candidate) => candidate.id === candidateId);

      if (foundCandidate) {
        await updateDoc(candidateRef, {
          votes: foundCandidate.votes + 1,
        });
      } 

      // Update the local state to reflect the new vote count
      setCandidates((prevCandidates) =>
        prevCandidates.map((candidate) =>
          candidate.id === candidateId
            ? { ...candidate, votes: candidate.votes + 1 }
            : candidate
        )
      );
    } catch (error) {
      console.error('Error updating votes:');
    }
  };
   
  return (
    <div>
      <Header />
      <div className="bg-gray-1000 py-12">
        <div className="container px-4">
          <div className="grid gap-6 md:gap-8 lg:gap-12 grid-cols-1 md:grid-cols-3 items-start">
            {candidates.map((candidate) => (
              <Card key={candidate.id}>
                <div className="flex flex-col h-full">
                  <CardContent className="flex-1">
                    <div className="flex justify-center items-center h-[200px]">
                      <Image
                        alt="Image"
                        className="rounded-full"
                        height="150"
                        src={candidate.imageSrc}
                        style={{
                          aspectRatio: "150/150",
                          objectFit: "cover",
                        }}
                        width="150"
                      />
                    </div>
                    <div className="text-center pt-4 pb-2">
                      <CardTitle>{candidate.name}</CardTitle>
                      <CardDescription>{`Votes: ${candidate.votes}`}</CardDescription>
                    </div>
                  </CardContent>
                  <CardFooter className="flex justify-center">
                    <Button
                      className="w-1/2 bg-black text-white"
                      variant="outline"
                      onClick={() => handleVoteClick(candidate.id)}
                    >
                      Vote
                    </Button>
                  </CardFooter>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
 }
 export default Vote;