/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n5PcaL2qzZg
 */
 import LivePoll from"@/components/live-poll"
 import { Header } from"@/components/shared/header"
 
 
 export default function Home() {
   return (
     <div>
       <Header />
       <LivePoll />
     </div>
   );
 }
 