/**
 * v0 by Vercel.
 * @see https://v0.dev/t/XcCpSGcmWbu
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
 /**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XcCpSGcmWbu
 */
  import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
  import Progress from "@/components/ui/progressbar"
  
  const LivePoll = () => {
    const candidates = [
      { name: 'Alice Brown', percentage: 25 },
      { name: 'Bob Smith', percentage: 15 },
      { name: 'Eve Johnson', percentage: 10 },
      { name: 'Omar Rodriguez', percentage: 20 },
      { name: 'Zara Lee', percentage: 30 },
    ];
  
    return (
      <div className="flex flex-col w-full items-center space-y-4">
        <div className="w-full max-w-sm">
          <Card>
            <CardHeader className="flex flex-col gap-1">
              <CardTitle>Who should win the election?</CardTitle>
              <CardDescription>Cast your vote for the best candidate!</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
              {candidates.map((candidate, index) => (
                <div className="flex flex-col gap-0.5" key={index}>
                  <div className="flex justify-between items-center">
                    <div>{candidate.name}</div>
                    <span className="text-xs font-semibold">{`${candidate.percentage}%`}</span>
                  </div>
                  <Progress value={candidate.percentage} />
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  export default LivePoll;
  