/**
 * v0 by Vercel.
 * @see https://v0.dev/t/XcCpSGcmWbu
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
 /**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XcCpSGcmWbu
 */
  "use client";
  import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
  import Progress from "@/components/ui/progressbar"
  import { collection, getDocs } from 'firebase/firestore';
  import {db} from '@/app/firebase/config'
  import { useEffect, useState } from 'react';
  import CandidateController from '@/controllers/CandidateController';

const LivePoll = () => {
  const candidates = CandidateController();

  return (
    <div className="flex flex-col w-full items-center space-y-4">
      <div className="w-full max-w-sm">
        <Card>
          <CardHeader className="flex flex-col gap-1">
            <CardTitle>Which is the best ice cream flavor?</CardTitle>
            <CardDescription>Cast your vote for the best flavor!</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            {candidates.map((candidate, index) => (
              <div className="flex flex-col gap-0.5" key={index}>
                <div className="flex justify-between items-center">
                  <div>{candidate.name}</div>
                  <span className="text-xs font-semibold">{`${candidate.percentage.toFixed(2)}%`}</span>
                </div>
                <Progress value={candidate.percentage} />
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default LivePoll;
