/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fys31EXTsov
 */
 import { Label } from "@/components/ui/label"
 import { Input } from "@/components/ui/input"
 import { Button } from "@/components/ui/button"
 import { Separator } from "@/components/ui/separator"
 import Link from "next/link"
 import { JSX, SVGProps, useState } from "react"
 import { Header } from "@/components/header"
import { useRouter } from "next/router"
 
 export function SignUp() {

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const router = useRouter();

    const submitRegistration = async () => {
    
        const domain = email.split("@")[1];

    try {
      const response = await fetch(`https://api.mailcheck.ai/domain/${domain}`);
      const data = await response.json();
      const valid = data.valid;

      if (valid) {
        // Call your register function or API endpoint here
        console.log("Registration successful");
      } else {
        alert("Invalid email. Try again.");
      }
    } catch (error) {
      console.error("Error checking email validity:", error);
    }


    router.push('/vote');
  };
  
   return (
     <div>
        <Header />
        <div className="mx-auto max-w-[350px] space-y-6">
            <div className="space-y-2 text-center">
                <h1 className="text-3xl font-bold">Register to Vote</h1>
                <p className="text-gray-500 dark:text-gray-400">Enter your account details to login.</p>
            </div>
            <div className="space-y-4">
                <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="m@example.com" required type="email" value={email} onChange={(e) => setEmail(e.target.value)}/>
                </div>
                <div className="space-y-2 relative">
                    <div className="space-y-1">
                        <Label htmlFor="password">Password</Label>
                        <div className="relative">
                            <Input id="password" required type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
                            <div className="flex items-center -translate-y-1.5 absolute right-2 top-1/2 transform -translate-y-1/2">
                                <Button
                                aria-label="Toggle password visibility"
                                className="h-8 p-1.5 -translate-y-0.5 w-8"
                                variant="ghost"
                                >
                                    <EyeIcon className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
                <Button className="w-full" type="button" onClick={submitRegistration}>
                Login
                </Button>
            </div>
            <Separator className="mb-0" />
            <div className="space-y-2 text-center">
                <p className="text-sm">
                Already registered? 
                <Link className="underline" href="/log-in">
                    Login
                </Link>
                </p>
            </div>
        </div>
     </div>
     
   )
 }
 
 
 function EyeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
   return (
     <svg
       {...props}
       xmlns="http://www.w3.org/2000/svg"
       width="24"
       height="24"
       viewBox="0 24"
       fill="none"
       stroke="currentColor"
       strokeWidth="2"
       strokeLinecap="round"
       strokeLinejoin="round"
     >
       <path d="M2 12s3-7 10-7 10 7 7-3 7-10 7-10-7-10-7Z" />
       <circle cx="12" cy="12" r="3" />
     </svg>
   )
 }

 export default SignUp;